Added UI for registration and code conformation (logo placeholder)
gabilic/SportLoc pull request #2
Opened 2018-10-30 18:07 UTC by fcrnko

UI for registration and UI for code conformation with all design
elements except logo are created (logo needs to be added)

2018-10-30 18:57 UTC, ZMehanovic requested changes
Registration confirmation is a feature we will not be using and it should be removed, otherwise it looks ok

2018-10-31 17:09 UTC, vglozinic requested changes
This is generally alright with small changes that need to be made for this merge.

2018-10-31 17:09 UTC, vglozinic commented on app/src/main/java/hr/foi/air/sportloc/MainActivity.java
> +        setContentView(R.layout.activity_registration);
This should be for reason stated before
```suggestion
        setContentView(R.layout.activity_main);
```

2018-10-31 17:09 UTC, vglozinic commented on app/src/main/res/values/strings.xml
> +    <string name="ivLogo_description">Logo Slika</string>
All string names should be in alphabetical order

2018-10-31 17:09 UTC, vglozinic commented on app/src/main/AndroidManifest.xml
>          <activity android:name=".MainActivity">
Your test activity can be run through this manifest. Simply replace .MainActivity with your activity and it should start with the activity you want to test. This is so not to disturb MainActivity which will have code in it.

2018-10-31 17:09 UTC, vglozinic commented on app/src/main/java/hr/foi/air/sportloc/RegistrationConfirmationActivity.java
> +package hr.foi.air.sportloc;
As stated, this class will be removed because it will be implemented as a fragment.

2018-10-31 17:09 UTC, vglozinic commented on app/src/main/res/layout/activity_registration_confirmation.xml
> +<?xml version="1.0" encoding="utf-8"?>
Keep the code for this class somewhere in a text file so we can retrieve it if necessary, otherwise delete it for reasons stated before.

2018-10-31 17:09 UTC, vglozinic commented on app/src/main/res/layout/activity_registration.xml
> +            <Spinner
It would be better to put two buttons here, as show on wireframe. That way the user can select them and you don't need to have a drop down menu.

2018-10-31 17:09 UTC, vglozinic commented on app/src/main/res/layout/activity_registration.xml
> +            <Button
REMINDER: Be sure to remove attributes and add style once button styles have been implemented.

2018-10-31 17:09 UTC, vglozinic commented on app/src/main/res/layout/activity_registration.xml
> +            <EditText
This name should be _etvName_, don't know why the name of the person is Code.

2018-10-31 17:09 UTC, vglozinic commented on app/src/main/res/layout/activity_registration.xml
> +            <EditText
It is not yet sure wether this will be a picker (list of years) or simple edit text view. Leave it as it is for now.

2018-11-08 19:13 UTC, ZMehanovic requested changes
I would strongly advise that you use butterknife as it is a very useful tool which can help simplify your code making it easier to write and easier to understand. Also I would like to note that there are other ways to format a date in java instead of using string concatenation, date setting and formatting will most likely be used in other parts of the application so it would probably be best to extract format to a different helper class so that everyone can use the same format regardless of location, below is one example of how you can set up a simple date format and use it to get wanted result. 
SimpleDateFormat simpledateformat = new SimpleDateFormat("dd/MM/yy");
Calendar newDate = Calendar.getInstance();
newDate.set(year, month, day);
String selectedDate = simpledateformat.format(newDate.getTime());

2018-11-10 14:38 UTC, vglozinic requested changes
There are still some changes to be made, check for them in the comments.

2018-11-10 14:38 UTC, vglozinic commented on app/src/main/AndroidManifest.xml
> +        <activity android:name=".RegistrationConfirmationActivity"></activity>
Remove Confirmation Activity from manifest, as it is not present in application.

2018-11-10 14:38 UTC, vglozinic commented on app/src/main/java/hr/foi/air/sportloc/RegistrationActivity.java
> +        mDisplayDate = (TextView) findViewById(R.id.tvDate);
What Zlatko said, Butterknife would be a good thing here.

2018-11-10 14:38 UTC, vglozinic commented on app/src/main/java/hr/foi/air/sportloc/RegistrationActivity.java
> +        mDateSetListener = new DatePickerDialog.OnDateSetListener() {
Read what Zlatko said about different use of date formatting and separating date functions into other class.

2018-11-10 14:38 UTC, vglozinic commented on app/src/main/res/values/strings.xml
>  <resources>
Date names should be in alphabetical order.

2018-11-10 14:38 UTC, vglozinic commented on app/src/main/res/layout/activity_registration.xml
> +<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
Changed IDs to prefix_element as in XML standard. Make sure to change it in your next push.

2018-11-10 14:38 UTC, vglozinic commented on app/src/main/res/layout/activity_registration.xml
> +                android:id="@+id/button"
Button id should be _btn_register_.

2018-11-27 19:52 UTC, vglozinic submitted a review, later dismissed

2018-11-28 14:38 UTC, ZMehanovic submitted a review, later dismissed

2018-11-28 15:02 UTC, ZMehanovic approved these changes
Seems ok, there are still a couple of issues which need to be fixed but as agreed it will be addressed in other tasks.

2018-11-28 15:02 UTC, merged