Created UI for profile
gabilic/SportLoc pull request #3
Opened 2018-10-30 18:15 UTC by ibogovic

Created UI for user profile and UI for profile configuration

2018-10-30 19:04 UTC, ZMehanovic requested changes
Other user, user profile and edit profile activities should be combined into a single activity as they all show pretty much the same information, different views can be done through the use of fragments.

2018-10-31 17:38 UTC, vglozinic requested changes
Everything looks good, except EditProfileActivity and OtherUserActivity should be removed. Edit profile will be made with fragment and other user look will be made with hidden elements. Other user and edit profile UI has not been reviewed for reason above.

2018-10-31 17:38 UTC, vglozinic commented on app/src/main/AndroidManifest.xml
> +        <activity android:name=".EditProfileActivity">
Before commit this should be returned to it's original state. Otherwise it's OK.

2018-10-31 17:38 UTC, vglozinic commented on app/src/main/res/layout/activity_profile.xml
> +    <ImageView
HINT: This isn't in the wireframe, check for updates on wiki.

2018-10-31 17:38 UTC, vglozinic commented on app/src/main/res/layout/activity_profile.xml
> +    <TextView
HINT: It would be good to dock it to constraint layout with 16dp margin on right side.

2018-10-31 17:38 UTC, vglozinic commented on app/src/main/res/layout/activity_profile.xml
> +    <ImageButton
This should be just a regular button, check out updated wireframe on wiki.

2018-10-31 17:38 UTC, vglozinic commented on app/src/main/res/layout/activity_profile.xml
> +    <TextView
This should be in this activity, check out wireframe on wiki.

2018-10-31 17:38 UTC, vglozinic commented on app/src/main/res/layout/activity_profile.xml
> +    <TextView
This should go bellow gender and age text view, check wireframe on wiki.

2018-10-31 17:38 UTC, vglozinic commented on app/src/main/res/layout/activity_profile.xml
> +    <Button
This should be hidden for now, other three shown buttons are shown on wireframe.
Also, consider putting button text in lowercase.

2018-10-31 17:38 UTC, vglozinic commented on app/src/main/res/values/strings.xml
>  <resources>
String names should be in alphabetical order.

2018-11-08 19:25 UTC, ZMehanovic requested changes
manifest should remain the way it was before (linked to main activity, changes for local testing should remain only locally), according to our naming convention scrollView components should start with sv instead of scrollView, strings file shuld be organized alphabetically, there is link on slack for a simple android studio plugin which can do this for you.

2018-11-10 14:55 UTC, vglozinic requested changes
Several things should be changed, requested for another push.

2018-11-10 14:55 UTC, vglozinic commented on app/src/main/AndroidManifest.xml
> +        <activity android:name=".EditProfileActivity">
Remove this activity as it is not present in application.

2018-11-10 14:55 UTC, vglozinic commented on app/src/main/AndroidManifest.xml
> +        <activity android:name=".OtherUserActivity"></activity>
Remove this activity as it is not present in application.

2018-11-10 14:55 UTC, vglozinic commented on app/src/main/res/layout/activity_profile.xml
> +    <ScrollView
Don't forget to change names to XML standard in naving convention.

2018-11-10 14:55 UTC, vglozinic commented on app/src/main/res/layout/activity_profile.xml
> +        android:id="@+id/tvGenderAge2"
This should be _tv_username_ and not GenderAge2.

2018-11-10 14:55 UTC, vglozinic commented on app/src/main/res/layout/activity_profile.xml
> +        android:layout_marginEnd="9dp"
Margin top should also be a good idea.

2018-11-10 14:55 UTC, vglozinic commented on app/src/main/res/layout/activity_profile.xml
> +                android:id="@+id/tvProfilePhotoTitle"
No need for this element, check out wireframe.

2018-11-10 14:55 UTC, vglozinic commented on app/src/main/res/layout/activity_profile.xml
> +                android:id="@+id/btnChoseProfilePhoto"
No need for this element, check out wireframe.

2018-11-10 14:55 UTC, vglozinic commented on app/src/main/res/layout/activity_profile.xml
> +                android:id="@+id/etvSurname"
Pop this element below name element.

2018-11-28 15:05 UTC, ZMehanovic approved these changes

2018-11-28 15:09 UTC, vglozinic approved these changes
Changes to be made for strings in another pull

2018-11-28 15:09 UTC, merged